### ISSUE TITLE
I was wondering if might help us

### ISSUE THREAD

**Issue by jweiland1** [urish/java-ast#19]
I am the Director for the FIRST Tech Challenge in Illinois. We are working on methods to translate  our java code to java script.  . The robot simulator is at https://www.vrobotsim.online/homepage.html . The Virtual Robot Simulator (VRS-and [how to use it](https://youtu.be/HvywykxdrBU)) teaches students how to code in a dynamic process that replicates the FIRST Tech Challenge game environment.  Right now we hard code the “java-js dictionary”.  I’m thinking that there might be a better way. I understand that FTC SIM Canada pixel pad uses one of your translators to move Java code to Java script.. I have a similar problem but I need help making it happen. Jonathan Weiland <jweiland@firstillinoisrobotics.org>

**Comment by urish** [comment]
Very cool simulator!

Unfortunately, I'm not really able to help here - you might want to check out https://teavm.org/ as a way to compile Java into JavaScript.
